// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/hot-topic/{community}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get hot topics",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "HotTopic"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "get lastest hot topics. value is true",
                        "name": "latest",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.HotTopicsDTO"
                        }
                    }
                }
            }
        },
        "/v1/hot-topic/{community}/solution": {
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "add topic solution",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "HotTopic"
                ],
                "summary": "Add",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToAddSolution"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/not-hot-topic/{community}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get worthless hot topics",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "NotHotTopic"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.NotHotTopicsDTO"
                        }
                    }
                }
            }
        },
        "/v1/topic-review/{community}": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get topics to review",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "TopicReview"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.TopicsToReviewDTO"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "update the selected topics",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "TopicReview"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToUpdateSelected"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "upload topics to review",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "TopicReview"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.reqToReview"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/topic-review/{community}/publish": {
            "get": {
                "security": [
                    {
                        "Internal": []
                    }
                ],
                "description": "get topics to publish",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "TopicReview"
                ],
                "summary": "GetTopicsToPublish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lowercase community name, like openubmc, cann",
                        "name": "community",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.HotTopicsDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.DiscussionSourceInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "source_closed": {
                    "type": "boolean"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "app.HotTopicsDTO": {
            "type": "object",
            "properties": {
                "topics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.hotTopicDTO"
                    }
                }
            }
        },
        "app.NotHotTopicsDTO": {
            "type": "object",
            "properties": {
                "topics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.notHotTopicDTO"
                    }
                }
            }
        },
        "app.OptionalTopic": {
            "type": "object",
            "properties": {
                "discussion": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/app.DiscussionSourceInfo"
                        }
                    }
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "app.TopicsToReviewDTO": {
            "type": "object",
            "properties": {
                "cadidates": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/domain.TopicToReview"
                        }
                    }
                },
                "selected": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TopicToReview"
                    }
                }
            }
        },
        "app.hotTopicDTO": {
            "type": "object",
            "properties": {
                "dss": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DiscussionSource"
                    }
                },
                "id": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/app.statusLogDTO"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "app.notHotTopicDTO": {
            "type": "object",
            "properties": {
                "dss": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DiscussionSourceInfo"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "app.statusLogDTO": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.reqToAddSolution": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.OptionalTopic"
                    }
                }
            }
        },
        "controller.reqToReview": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.OptionalTopic"
                    }
                }
            }
        },
        "controller.reqToUpdateSelected": {
            "type": "object",
            "properties": {
                "selected": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TopicToReview"
                    }
                }
            }
        },
        "domain.DiscussionSource": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imported_at": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.DiscussionSourceInfo": {
            "type": "object",
            "properties": {
                "closed": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.DiscussionSourceToReview": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imported_at": {
                    "type": "string"
                },
                "source_closed": {
                    "type": "boolean"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.TopicToReview": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "dss": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DiscussionSourceToReview"
                    }
                },
                "ht_id": {
                    "description": "it is not empty if the topic is the last host topic",
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "resolved": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Internal": {
            "description": "Type \"Internal\" followed by a space and internal token.",
            "type": "apiKey",
            "name": "TOKEN",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
